### ISSUE TITLE
Update URLs for Akamai SureRoute

### ISSUE THREAD

**Issue by rmatherly** [CyberSource/cybersource-sdk-dotnet#13]
We are being notified that the URLs are changing to support Akamai SureRoute:

Test Environment: ics2wstesta.ic3.com
Production Environment: ics2wsa.ic3.com

I can download the source and make this change myself, but since everyone will need to switch by July 1, 2016, it would be nice to have a separate branch and zip download for this during the transition period.

**Comment by moojjoo** [comment]
I second the issue above.   If anybody needs to know how to change this download source code and expand the CyberSourceClients (Project) > ServiceReferences and be sure to update the NVPServiceReference & SoapServiceReference ----- REBUILD

Also be sure to update the CyberSource.Clients.dll.config (I am unsure if this matters, but I changed to the URLs above and passed on TEST), have not changed production to date, but will post back when I do. 

Remove Old DLLs and replace with new DLLs (I had to make sure to change build to "Any CPU"


Obtain and Install Certificates Windows Server 2008 R2 (This was fun to figure out which I could get paid for providing the instructions --- HINT HINT CyberSource)

1. Open Chrome on the Windows Server and go to https://ics2wsa.ic3.com right click on padlock > Connections tab > Certificate Information > Certification Path > Copy to File > 

2. Start at the top of the chain GeoTrust Global CA > View Certificate > Details Tab > Copy to File...

3. Save as C:\CyberSourceCerts\WebSiteName_Cert_1.cer

Repeat for GeoTrust SSL CA - G3 --- Save as C:\CyberSourceCerts\WebStieName_Cert_2.cer


On Windows Server 2008 R2 click Start > search type MMC > Open MMC.exe > File Add Certificates Snap On Computer Account > Local computer > OK > Double Click Certificates > Trusted Root Certification Authorities > More Actions > All Tasks > Import...   (Import CyberSourceCerts\WebSiteName_Cert_1.cer > Repeat for C:\CyberSourceCerts\WebStieName_Cert_2.cer.

If this is incorrect I would like CyberSource to post the correct instructions.

**Comment by tgandersen** [comment]
Hey @moojjoo, just curious if you ever rolled this out to production and whether or not it worked using your particular steps above?  I'm in the middle of updating our system and, as you and the OP have said, CyberSource's documentation leaves quite a bit to be desired on this particular update.

**Comment by moojjoo** [comment]
It worked on DEV and TEST, but have not gotten it implemented in PRODUCTION yet.  Glad you reminded me.  I will work on this tonight to see the results.

**Comment by afinzel** [comment]
Why is Cybersource not updating this and pushing a new version to Nuget?

**Comment by moojjoo** [comment]
Please see my comments above with how to fix this.

**Comment by afinzel** [comment]
Hey Moojjoo,

While I appreciate your change will work.  The whole point of nuget is that you don't have to download the source and manually update it.  This should be fixed by Cybersource, or at least merge your PR.  Support have said, they will not be updating this repo.

**Comment by moojjoo** [comment]
Are you kidding me?  I hope they merge the change.  I am writing a letter requesting compensation for their lack of due diligence and my time for providing a solution.  Wish me luck!!! I need a bonus.  Google pays out for this type of work maybe they will to.  :+1:   CyberSource are going to have a lot of very unhappy .NET Simple Order API SDK unhappy customers come June 30th.

**Comment by afinzel** [comment]
Wow its been 10 days now and still no comment from Cybersource.  Come on ylokhand

**Comment by moojjoo** [comment]
https://www.nuget.org/packages/UnofficialCyberSourceByMoojjoo/

**Comment by Uniphix** [comment]
I am still pretty shocked, for such a major Payment Gateway company not to keep their SDK up to date, especially when its in 30 days that this will occur.

*SMH*

**Comment by amie-gao** [comment]
The issue has been addressed in the new release.

**Comment by moojjoo** [comment]
How has this been addressed with the WSDL is still point to - <wsdl:service name="NVPTransactionProcessor">
    <wsdl:documentation>CyberSource Web Service</wsdl:documentation>
    <wsdl:port name="portNVP" binding="tns:INVPTransactionProcessor">
      <soap:address location="**https://ics2wstest.ic3.com/commerce/1.x/transactionProcessor**" />
    </wsdl:port>
  </wsdl:service>


Instead of - 
 <wsdl:service name="NVPTransactionProcessor">
    <wsdl:documentation>CyberSource Web Service</wsdl:documentation>
    <wsdl:port name="portNVP" binding="tns:INVPTransactionProcessor">
      <soap:address location="**https://ics2wstesta.ic3.com/commerce/1.x/transactionProcessor**" />
    </wsdl:port>
  </wsdl:service>

**Comment by amie-gao** [comment]
you need to enable the service parameter in the config file. please check the readme out for the details.
