### ISSUE TITLE
Sign CyberSource.Clients library

### ISSUE THREAD

**Issue by runecasters** [CyberSource/cybersource-sdk-dotnet#41]
We have a requirement of using signed libraries with our project. I see the CyberSource.Base library is signed, but not the CyberSource.Clients library. Can this be signed as well?

We're currently signing and compiling the library ourselves to get around this, but we'd prefer to use NuGet to make keeping up with updates simpler.

**Comment by amie-gao** [comment]
This is related to NuGet and release process. During release NuGet sign the release binaries. 
We can investigate this issue and take care of this in our future releases.
