### ISSUE TITLE
README.md Missing Supported API Version

### ISSUE THREAD

**Issue by henderni** [CyberSource/cybersource-sdk-dotnet#52]
Hello, the README.md file says "The version of the CyberSource Web Services API supported by the clients is indicated at the top of this README" but then there is no version listed at the top of the README. Please list a version or remove this line. I came here curious about which version this package supported since it hadn't been updated in 8 months and wasn't able to easily determine that from the README file which was disappointing. Thanks!

**Comment by duncancoppedge** [comment]
To save someone else looking around.. as of now it's v1.109 which is 4 years old, but it's pretty easy to update after you clone the repo.
- File with version in it: `https://github.com/CyberSource/cybersource-sdk-dotnet/blob/master/CyberSource/Client/Service References/NVPServiceReference/NVPCyberSourceTransactionWS.wsdl`
- NuGet 1.42 has v1.147 `urn:schemas-cybersource-com:transaction-data-1.147`  https://www.nuget.org/packages/CyberSource/1.4.2
- Latest version is 1.161 - https://ics2ws.ic3.com/commerce/1.x/transactionProcessor/

**Comment by mahendya1002** [comment]
Thanks it will be fixed in 1.4.3
